import * as SQLite from 'expo-sqlite';

const db = SQLite.openDatabaseSync('medicamentos.db');

export const initDatabase = () => {
  db.execSync(`DROP TABLE IF EXISTS medicamentos;`);
  
  db.execSync(`
    CREATE TABLE IF NOT EXISTS medicamentos (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      nombre TEXT,
      categoria TEXT,
      descripcion TEXT,
      uso TEXT,
      enfermedades TEXT,
      imagen TEXT,
      advertencia TEXT,
      dosificacion TEXT,
      efectos TEXT,
      contraindicaciones TEXT
    );
  `);

  const medicamentos = [
    // ==================== HOSPITAL (1-120) ====================
    ['Paracetamol', 'hospital', 'Analgésico y antipirético', 'Dolor leve a moderado, fiebre', 'Dolor de cabeza|Resfriado común|Fiebre|Dolor dental', 'https://img.icons8.com/color/96/000000/tablets.png', 'No exceder la dosis. Daño hepático por sobredosis.', '500-1000 mg cada 6-8 horas. Máx 4000 mg/día.', 'Náuseas|Vómitos|Daño hepático', 'Enfermedad hepática|Alcoholismo'],
    ['Ibuprofeno', 'hospital', 'Antiinflamatorio no esteroide', 'Dolor e inflamación', 'Artritis|Dolor dental|Fiebre|Dolor menstrual', 'https://img.icons8.com/color/96/000000/medicine.png', 'Tomar con alimentos. Evitar uso prolongado.', '400-600 mg cada 6-8 horas. Máx 2400 mg/día.', 'Dolor estomacal|Náuseas|Mareos|Sangrado GI', 'Úlcera péptica|Insuficiencia renal|Embarazo'],
    ['Amoxicilina', 'hospital', 'Antibiótico penicilínico', 'Infecciones bacterianas', 'Faringitis|Bronquitis|Neumonía|Otitis', 'https://img.icons8.com/color/96/000000/antibiotic.png', 'Completar tratamiento. No usar en infecciones virales.', '500 mg cada 8 horas u 875 mg cada 12 horas.', 'Diarrea|Náuseas|Erupción cutánea|Vómitos', 'Alergia a penicilinas|Mononucleosis'],
    ['Morfina', 'hospital', 'Analgésico opioide potente', 'Dolor severo', 'Dolor oncológico|Dolor postoperatorio|Infarto', 'https://img.icons8.com/color/96/000000/medicine.png', 'Uso hospitalario exclusivo. Alto potencial de dependencia.', '2-10 mg IV cada 4 horas según necesidad.', 'Depresión respiratoria|Náuseas|Estreñimiento|Dependencia', 'Insuficiencia respiratoria|Íleo|Alcoholismo'],
    ['Ceftriaxona', 'hospital', 'Cefalosporina', 'Infecciones bacterianas graves', 'Neumonía|Meningitis|Sepsis|Gonorrea', 'https://img.icons8.com/color/96/000000/antibiotic.png', 'Uso hospitalario. No mezclar con calcio.', '1-2 g cada 24 horas IV o IM.', 'Diarrea|Dolor sitio inyección|Erupción', 'Alergia a cefalosporinas|Hiperbilirrubinemia'],
    ['Vancomicina', 'hospital', 'Glicopéptido', 'Infecciones resistentes', 'MRSA|Colitis C. difficile|Endocarditis', 'https://img.icons8.com/color/96/000000/antibiotic.png', 'Monitoreo de niveles. Riesgo nefrotoxicidad.', '15-20 mg/kg cada 8-12 horas IV.', 'Nefrotoxicidad|Ototoxicidad|Síndrome hombre rojo', 'Hipersensibilidad|Hipoacusia|Insuficiencia renal'],
    ['Dexametasona', 'hospital', 'Corticoesteroide', 'Inflamación severa', 'Edema cerebral|Alergias graves|Asma severa|COVID-19', 'https://img.icons8.com/color/96/000000/steroid.png', 'No suspender bruscamente. Monitorear glucosa.', '4-20 mg/día IV o IM.', 'Hiperglucemia|Retención líquidos|Insomnio', 'Infección fúngica|Hipersensibilidad'],
    ['Propofol', 'hospital', 'Anestésico general', 'Inducción anestésica', 'Cirugías|Sedación UCI|Procedimientos', 'https://img.icons8.com/color/96/000000/anesthesia.png', 'Uso exclusivo anestesiólogo. Monitoreo continuo.', '1.5-2.5 mg/kg IV inducción.', 'Hipotensión|Depresión respiratoria|Apnea', 'Alergia|Hiperlipidemia'],
    ['Furosemida', 'hospital', 'Diurético de asa', 'Edema e hipertensión', 'Edema pulmonar|Insuficiencia cardíaca|IRC', 'https://img.icons8.com/color/96/000000/kidney.png', 'Monitorear electrolitos. Riesgo de hipokalemia.', '20-80 mg/día IV o IM.', 'Hipokalemia|Deshidratación|Ototoxicidad', 'Anuria|Insuficiencia renal grave'],
    ['Metoprolol', 'hospital', 'Betabloqueador', 'Hipertensión y arritmias', 'Hipertensión|Insuficiencia cardíaca|Angina|Arritmias', 'https://img.icons8.com/color/96/000000/heart.png', 'No suspender bruscamente. Monitorear FC.', '50-100 mg/día en 1-2 dosis.', 'Fatiga|Bradicardia|Hipotensión|Mareos', 'Bradicardia severa|Shock cardiogénico|Asma'],
    ['Enoxaparina', 'hospital', 'Anticoagulante', 'Prevención de trombosis', 'TVP|Embolia pulmonar|Cirugías|Angina', 'https://img.icons8.com/color/96/000000/blood.png', 'Riesgo de sangrado. No administrar IM.', '40 mg SC al día profilaxis. 1 mg/kg cada 12 horas tratamiento.', 'Hematomas|Sangrado|Trombocitopenia', 'Sangrado activo|Trombocitopenia|Endocarditis'],
    ['Midazolam', 'hospital', 'Benzodiazepina', 'Sedación y ansiolisis', 'Sedación consciente|Ansiedad|Premedicación', 'https://img.icons8.com/color/96/000000/sedative.png', 'Riesgo depresión respiratoria. No mezclar con alcohol.', '0.5-2 mg IV sedación.', 'Depresión respiratoria|Hipotensión|Somnolencia', 'Glaucoma|Miastenia gravis|Embarazo'],
    ['Losartán', 'hospital', 'ARA II', 'Hipertensión', 'Hipertensión|Protección renal|Insuficiencia cardíaca', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Monitorear potasio. Evitar embarazo.', '50 mg una vez al día. Máx 100 mg.', 'Mareos|Hipotensión|Hiperkalemia', 'Embarazo|Estenosis renal|Insuficiencia renal'],
    ['Amiodarona', 'hospital', 'Antiarritmico', 'Arritmias ventriculares', 'Taquicardia ventricular|Fibrilación auricular', 'https://img.icons8.com/color/96/000000/heart.png', 'Monitoreo hepático, tiroideo y pulmonar.', '100-200 mg/día oral mantenimiento.', 'Fibrosis pulmonar|Hepatotoxicidad|Hipertiroidismo', 'Bradicardia severa|Enfermedad tiroidea'],
    ['Insulina Glargina', 'hospital', 'Insulina larga duración', 'Diabetes', 'Diabetes tipo 1|Diabetes tipo 2', 'https://img.icons8.com/color/96/000000/insulin.png', 'Monitoreo de glucosa. Riesgo de hipoglucemia.', '10 U o 0.2 U/kg SC una vez al día.', 'Hipoglucemia|Lipodistrofia|Aumento de peso', 'Hipoglucemia|Hipersensibilidad'],
    ['Omeprazol', 'hospital', 'IBP', 'Protección gástrica', 'Reflujo|Gastritis|Úlcera|ERGE', 'https://img.icons8.com/color/96/000000/stomach.png', 'Tomar antes del desayuno. Uso prolongado: riesgo B12.', '20-40 mg/día antes del desayuno.', 'Cefalea|Náuseas|Diarrea|Deficiencia B12', 'Hipersensibilidad|Enfermedad hepática grave'],
    ['Ondansetrón', 'hospital', 'Antiemético', 'Náuseas y vómitos', 'Quimioterapia|Postoperatorio|Náuseas severas', 'https://img.icons8.com/color/96/000000/nausea.png', 'Riesgo de prolongación QT.', '4-8 mg IV u oral cada 8-12 horas.', 'Cefalea|Estreñimiento|Prolongación QT', 'Hipersensibilidad|Prolongación QT congénita'],
    ['Clopidogrel', 'hospital', 'Antiplaquetario', 'Prevención de trombosis', 'Infarto|ACV|Enfermedad arterial|Post-stent', 'https://img.icons8.com/color/96/000000/heart.png', 'Riesgo de sangrado. Suspender antes de cirugía.', '75 mg una vez al día.', 'Sangrado|Hematomas|Diarrea|Trombocitopenia', 'Sangrado activo|Úlcera péptica|Insuficiencia hepática'],
    ['Atorvastatina', 'hospital', 'Estatina', 'Colesterol alto', 'Hipercolesterolemia|Triglicéridos|Prevención cardiovascular', 'https://img.icons8.com/color/96/000000/cholesterol.png', 'Tomar noche. Reportar dolor muscular. Evitar toronja.', '10-80 mg una vez al día por la noche.', 'Dolor muscular|Debilidad|Rabdomiólisis', 'Enfermedad hepática|Embarazo|Lactancia'],
    ['Aspirina', 'hospital', 'Antiplaquetario', 'Prevención cardiovascular', 'Prevención infarto|Prevención ACV|Dolor|Fiebre', 'https://img.icons8.com/color/96/000000/heart.png', 'No dar a menores 18 años (Reye). Tomar con alimentos.', '100 mg/día prevención. 500-1000 mg cada 6-8 horas dolor.', 'Sangrado GI|Zumbidos|Síndrome de Reye', 'Úlcera|Hemofilia|Asma|Menores 18 años|Embarazo'],
    ['Ciprofloxacino', 'hospital', 'Fluoroquinolona', 'Infecciones bacterianas', 'Infecciones urinarias|Neumonía|Sinusitis', 'https://img.icons8.com/color/96/000000/antibiotic.png', 'Riesgo rotura tendones. Evitar sol. Hidratar.', '250-750 mg cada 12 horas.', 'Náuseas|Diarrea|Rotura tendones|Fotosensibilidad', 'Embarazo|Lactancia|Menores 18 años|Epilepsia'],
    ['Levotiroxina', 'hospital', 'Hormona tiroidea', 'Hipotiroidismo', 'Hipotiroidismo|Bocio|Cáncer tiroides', 'https://img.icons8.com/color/96/000000/thyroid.png', 'Tomar en ayunas 30-60 min antes desayuno.', '1.6 mcg/kg/día.', 'Palpitaciones|Taquicardia|Insomnio|Pérdida peso', 'Tirotoxicosis|Infarto reciente|Insuficiencia suprarrenal'],
    ['Enalapril', 'hospital', 'IECA', 'Hipertensión', 'Hipertensión|Insuficiencia cardíaca|Nefropatía diabética', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Monitorear función renal y potasio. Riesgo tos.', '5-40 mg/día en 1-2 dosis.', 'Tos seca|Mareos|Hipotensión|Angioedema', 'Embarazo|Estenosis renal|Angioedema previo'],
    ['Metoclopramida', 'hospital', 'Procinético', 'Náuseas y reflujo', 'Gastroparesia|Náuseas|Vómitos|Reflujo', 'https://img.icons8.com/color/96/000000/stomach.png', 'No usar >12 semanas. Riesgo discinesia tardía.', '10 mg cada 6-8 horas. Máx 30 mg/día.', 'Somnolencia|Discinesia|Síndrome extrapiramidal', 'Hemorragia GI|Obstrucción|Parkinson|Epilepsia'],
    ['Prednisona', 'hospital', 'Corticoesteroide', 'Enfermedades autoinmunes', 'Artritis reumatoide|Lupus|Asma|Crohn', 'https://img.icons8.com/color/96/000000/steroid.png', 'No suspender bruscamente. Monitorear glucosa y presión.', '5-60 mg/día. Dosis mínima efectiva.', 'Aumento peso|Hiperglucemia|Osteoporosis|Cataratas', 'Infección sistémica|Herpes ocular|Tuberculosis'],
    ['Warfarina', 'hospital', 'Anticoagulante', 'Prevención de trombosis', 'Fibrilación auricular|TVP|Válvulas mecánicas', 'https://img.icons8.com/color/96/000000/blood.png', 'Monitoreo INR. Evitar cambios bruscos vitamina K.', '2-10 mg/día. Ajustar según INR (2-3).', 'Sangrado|Hematomas|Necrosis cutánea', 'Embarazo|Sangrado activo|Hipertensión severa|Enfermedad hepática'],
    ['Diazepam', 'hospital', 'Benzodiazepina', 'Ansiedad y relajante muscular', 'Ansiedad|Contracturas|Sedación|Convulsiones', 'https://img.icons8.com/color/96/000000/anxiety.png', 'Riesgo dependencia. No mezclar alcohol.', '2-10 mg cada 6-12 horas.', 'Somnolencia|Mareos|Dependencia|Amnesia', 'Glaucoma|Miastenia gravis|Insuficiencia respiratoria'],
    ['Amlodipino', 'hospital', 'Bloqueador calcio', 'Hipertensión y angina', 'Hipertensión|Angina|Enfermedad coronaria', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Tomar misma hora. Precaución en hepatopatía.', '5-10 mg una vez al día.', 'Edema tobillos|Cefalea|Mareos|Rubor', 'Hipotensión severa|Shock cardiogénico|Estenosis aórtica'],
    ['Simvastatina', 'hospital', 'Estatina', 'Colesterol alto', 'Hipercolesterolemia|Prevención cardiovascular', 'https://img.icons8.com/color/96/000000/cholesterol.png', 'Tomar noche. Reportar dolor muscular.', '10-40 mg/día por la noche.', 'Dolor muscular|Debilidad|Elevación enzimas hepáticas', 'Enfermedad hepática|Embarazo|Lactancia'],
    ['Hidroclorotiazida', 'hospital', 'Diurético tiazídico', 'Hipertensión y edema', 'Hipertensión|Edema leve|Nefrolitiasis', 'https://img.icons8.com/color/96/000000/kidney.png', 'Tomar mañana. Monitorear electrolitos.', '12.5-50 mg/día.', 'Hipokalemia|Hiperglucemia|Hiperuricemia', 'Anuria|Insuficiencia renal grave|Hipersensibilidad sulfonamidas'],
    ['Espironolactona', 'hospital', 'Diurético ahorrador K', 'Hipertensión y edema', 'Hipertensión|Insuficiencia cardíaca|Cirrosis|SOP', 'https://img.icons8.com/color/96/000000/kidney.png', 'Monitorear potasio. Riesgo hiperkalemia.', '25-100 mg/día.', 'Hiperkalemia|Ginecomastia|Dolor mamario', 'Insuficiencia renal|Hiperkalemia|Enfermedad Addison'],
    ['Pantoprazol', 'hospital', 'IBP', 'Protección gástrica', 'ERGE|Esofagitis|Úlcera|Zollinger-Ellison', 'https://img.icons8.com/color/96/000000/stomach.png', 'Tomar antes desayuno. No partir tableta.', '20-40 mg/día antes del desayuno.', 'Cefalea|Diarrea|Náuseas|Fracturas óseas', 'Hipersensibilidad|Insuficiencia hepática grave'],
    ['Clonazepam', 'hospital', 'Anticonvulsivante', 'Epilepsia y ansiedad', 'Epilepsia|Ansiedad severa|Trastorno pánico', 'https://img.icons8.com/color/96/000000/seizure.png', 'Riesgo dependencia. No suspender bruscamente.', '0.5-2 mg/día.', 'Somnolencia|Ataxia|Dependencia|Depresión', 'Insuficiencia hepática|Glaucoma|Miastenia gravis'],
    ['Propranolol', 'hospital', 'Betabloqueador', 'Hipertensión y migraña', 'Hipertensión|Angina|Migraña|Temblor|Hipertiroidismo', 'https://img.icons8.com/color/96/000000/heart.png', 'No suspender bruscamente. Precaución en asma.', '40-160 mg cada 12 horas.', 'Fatiga|Bradicardia|Depresión|Fenómeno Raynaud', 'Asma|Bradicardia severa|Shock cardiogénico'],
    ['Captopril', 'hospital', 'IECA', 'Hipertensión', 'Hipertensión|Insuficiencia cardíaca|Post-infarto', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Tomar 1 hora antes alimentos. Riesgo tos.', '12.5-50 mg cada 8-12 horas.', 'Tos|Mareos|Angioedema|Alteración gusto', 'Embarazo|Estenosis renal|Angioedema previo'],
    ['Digoxina', 'hospital', 'Glucósido cardíaco', 'Insuficiencia cardíaca y arritmias', 'Insuficiencia cardíaca|Fibrilación auricular', 'https://img.icons8.com/color/96/000000/heart.png', 'Monitoreo niveles. Riesgo toxicidad digitalica.', '0.125-0.25 mg/día.', 'Náuseas|Vómitos|Arritmias|Visión borrosa', 'Bloqueo AV|Miocardiopatía hipertrófica|Hipokalemia'],
    ['Metronidazol', 'hospital', 'Antibiótico', 'Infecciones anaerobias', 'Vaginosis|Giardiasis|Abscesos|Enfermedad Crohn', 'https://img.icons8.com/color/96/000000/antibiotic.png', 'Evitar alcohol durante y 48h después.', '250-500 mg cada 6-8 horas.', 'Sabor metálico|Náuseas|Neuropatía|Orina oscura', 'Embarazo primer trimestre|Enfermedad hepática'],
    ['Ketorolaco', 'hospital', 'AINE potente', 'Dolor moderado a severo', 'Dolor postoperatorio|Cólico renal|Migraña', 'https://img.icons8.com/color/96/000000/pain.png', 'Uso máximo 5 días. Riesgo sangrado GI.', '10-30 mg cada 6 horas IV/IM. Máx 120 mg/día.', 'Dolor estomacal|Sangrado GI|Insuficiencia renal', 'Úlcera|Insuficiencia renal|Asma|Menores 16 años'],
    ['Lorazepam', 'hospital', 'Benzodiazepina', 'Ansiedad y sedación', 'Ansiedad|Sedación|Estado epiléptico|Insomnio', 'https://img.icons8.com/color/96/000000/anxiety.png', 'Riesgo dependencia. No suspender bruscamente.', '1-2 mg cada 6-12 horas.', 'Somnolencia|Ataxia|Dependencia|Amnesia', 'Glaucoma|Miastenia gravis|Insuficiencia respiratoria'],
    ['Haloperidol', 'hospital', 'Antipsicótico', 'Psicosis y agitación', 'Esquizofrenia|Agitación|Delirium|Tourette', 'https://img.icons8.com/color/96/000000/psychiatry.png', 'Riesgo extrapiramidal. Monitorear QT.', '1-10 mg/día. Agitación: 2-5 mg IM.', 'Síndrome extrapiramidal|Sedación|Prolongación QT', 'Parkinson|Depresión SNC|QT prolongado'],
    ['Naloxona', 'hospital', 'Antagonista opioide', 'Reversión sobredosis opioides', 'Sobredosis opioides|Depresión respiratoria', 'https://img.icons8.com/color/96/000000/medicine.png', 'Vida media corta. Monitorizar re-narcotización.', '0.4-2 mg IV cada 2-3 minutos.', 'Síndrome abstinencia|Náuseas|Taquicardia', 'Dependencia opioides (causa abstinencia)'],
    ['Heparina', 'hospital', 'Anticoagulante', 'Anticoagulación rápida', 'TVP|Embolia pulmonar|Cirugías|Infarto', 'https://img.icons8.com/color/96/000000/blood.png', 'Monitoreo TTPA. Riesgo sangrado.', '5000-10000 U IV bolo, luego 1000-2000 U/hora.', 'Sangrado|Trombocitopenia|Osteoporosis', 'Sangrado activo|Trombocitopenia|Hipertensión severa'],

    // ==================== USO COTIDIANO ====================
    ['Loratadina', 'cotidiano', 'Antihistamínico no sedante', 'Alergias', 'Rinitis alérgica|Urticaria|Fiebre del heno', 'https://img.icons8.com/color/96/000000/allergy.png', 'No produce somnolencia. Evitar alcohol.', '10 mg una vez al día.', 'Dolor cabeza|Sequedad bucal|Fatiga', 'Hipersensibilidad|Insuficiencia hepática'],
    ['Cetirizina', 'cotidiano', 'Antihistamínico', 'Alergias', 'Rinitis|Urticaria|Conjuntivitis alérgica', 'https://img.icons8.com/color/96/000000/allergy.png', 'Puede causar somnolencia leve.', '10 mg una vez al día.', 'Somnolencia|Fatiga|Sequedad bucal', 'Insuficiencia renal grave|Embarazo'],
    ['Fexofenadina', 'cotidiano', 'Antihistamínico', 'Alergias estacionales', 'Rinitis alérgica|Urticaria crónica', 'https://img.icons8.com/color/96/000000/allergy.png', 'No tomar con jugo de toronja.', '180 mg una vez al día o 60 mg cada 12 horas.', 'Dolor cabeza|Náuseas|Mareos', 'Insuficiencia renal grave'],
    ['Desloratadina', 'cotidiano', 'Antihistamínico', 'Alergias crónicas', 'Rinitis|Urticaria crónica', 'https://img.icons8.com/color/96/000000/allergy.png', 'No produce somnolencia significativa.', '5 mg una vez al día.', 'Dolor cabeza|Sequedad bucal|Fatiga', 'Insuficiencia renal|Embarazo'],
    ['Naproxeno', 'cotidiano', 'AINE', 'Dolor e inflamación', 'Dolor menstrual|Dolor espalda|Artritis|Gota', 'https://img.icons8.com/color/96/000000/pain.png', 'Tomar con alimentos. No exceder 10 días.', '250-500 mg cada 8-12 horas. Máx 1250 mg/día.', 'Acidez|Náuseas|Mareos|Zumbidos', 'Úlcera|Insuficiencia renal|Asma|Embarazo'],
    ['Diclofenaco', 'cotidiano', 'AINE', 'Dolor muscular', 'Dolores musculares|Artritis|Dolor dental', 'https://img.icons8.com/color/96/000000/pain.png', 'Tomar con alimentos. Riesgo cardiovascular.', '50 mg cada 8 horas.', 'Dolor estomacal|Náuseas|Retención líquidos', 'Úlcera|Insuficiencia renal|Asma|Embarazo'],
    ['Vitamina C', 'cotidiano', 'Suplemento', 'Refuerzo inmunológico', 'Resfriados|Fatiga|Defensas bajas', 'https://img.icons8.com/color/96/000000/vitamin-c.png', 'Dosis altas: malestar estomacal.', '500-1000 mg al día.', 'Diarrea|Náuseas|Cálculos renales', 'Hemocromatosis|Cálculos renales'],
    ['Vitamina D', 'cotidiano', 'Suplemento', 'Salud ósea', 'Osteoporosis|Deficiencia vitamínica', 'https://img.icons8.com/color/96/000000/vitamin-d.png', 'No exceder dosis.', '400-2000 UI/día.', 'Náuseas|Hipercalcemia|Debilidad', 'Hipercalcemia|Insuficiencia renal'],
    ['Multivitamínico', 'cotidiano', 'Suplemento', 'Energía y defensas', 'Fatiga|Estrés|Vitaminas bajas', 'https://img.icons8.com/color/96/000000/vitamins.png', 'No exceder dosis.', '1 tableta al día con alimentos.', 'Náuseas leves|Orina amarilla', 'Hipervitaminosis|Insuficiencia renal'],
    ['Melatonina', 'cotidiano', 'Regulador sueño', 'Insomnio', 'Insomnio|Jet lag|Trabajo turnos', 'https://img.icons8.com/color/96/000000/sleep.png', 'Tomar 30-60 min antes acostarse.', '1-5 mg antes de acostarse.', 'Somnolencia matutina|Cefalea|Sueños vívidos', 'Enfermedad autoinmune|Epilepsia'],
    ['Bromazepam', 'cotidiano', 'Ansiolítico', 'Ansiedad', 'Ansiedad|Nerviosismo|Estrés', 'https://img.icons8.com/color/96/000000/anxiety.png', 'Riesgo dependencia. Uso corto plazo.', '1.5-6 mg cada 8-12 horas.', 'Somnolencia|Mareos|Dependencia', 'Miastenia gravis|Glaucoma|Insuficiencia hepática'],
    ['Loperamida', 'cotidiano', 'Antidiarreico', 'Diarrea', 'Diarrea del viajero|Diarrea viral', 'https://img.icons8.com/color/96/000000/diarrhea.png', 'No usar si fiebre o sangre en heces.', '4 mg inicial, luego 2 mg después cada deposición.', 'Estreñimiento|Mareos|Somnolencia', 'Diarrea con sangre|Fiebre|Menores 12 años'],
    ['Dimenhidrinato', 'cotidiano', 'Antimareo', 'Mareos y náuseas', 'Mareo por movimiento|Vértigo', 'https://img.icons8.com/color/96/000000/dizziness.png', 'Causa somnolencia. No conducir.', '50-100 mg cada 6-8 horas.', 'Somnolencia|Sequedad bucal|Visión borrosa', 'Glaucoma|Asma|Hipertrofia prostática'],
    ['Simeticona', 'cotidiano', 'Antiflatulento', 'Gases', 'Gases|Hinchazón abdominal|Indigestión', 'https://img.icons8.com/color/96/000000/gas.png', 'Tomar después comidas.', '40-125 mg después de comidas.', 'Ninguno significativo', 'Oclusión intestinal|Apendicitis'],
    ['Salbutamol', 'cotidiano', 'Broncodilatador', 'Asma', 'Asma|EPOC|Broncoespasmo', 'https://img.icons8.com/color/96/000000/asthma.png', 'Uso rescate. Si usa >2/semana consultar.', '1-2 inhalaciones cada 4-6 horas.', 'Temblores|Palpitaciones|Taquicardia', 'Taquiarritmias|Hipertiroidismo'],
    ['Omeprazol', 'cotidiano', 'IBP', 'Acidez estomacal', 'Acidez|Reflujo|Gastritis', 'https://img.icons8.com/color/96/000000/stomach.png', 'Tomar antes desayuno. No usar >14 días.', '20 mg/día antes del desayuno.', 'Dolor cabeza|Náuseas|Diarrea', 'Hipersensibilidad|Enfermedad hepática'],
    ['Ambroxol', 'cotidiano', 'Mucolítico', 'Flemas', 'Tos productiva|Bronquitis|EPOC', 'https://img.icons8.com/color/96/000000/mucus.png', 'Aumentar ingesta líquidos.', '30-60 mg cada 8 horas.', 'Náuseas|Dolor cabeza|Diarrea', 'Úlcera péptica|Embarazo primer trimestre'],
    ['Guaifenesina', 'cotidiano', 'Expectorante', 'Tos con flema', 'Bronquitis|Resfriados con flema', 'https://img.icons8.com/color/96/000000/mucus.png', 'Aumentar ingesta líquidos.', '200-400 mg cada 4 horas. Máx 2400 mg/día.', 'Náuseas|Dolor cabeza|Mareos', 'Hipersensibilidad|Tos crónica sin diagnóstico'],
    ['Ácido Acetilsalicílico', 'cotidiano', 'Antiplaquetario', 'Dolor y prevención', 'Dolor cabeza|Fiebre|Prevención infarto', 'https://img.icons8.com/color/96/000000/heart.png', 'No dar a menores 18 años.', '500-1000 mg cada 6-8 horas dolor. 100 mg/día prevención.', 'Dolor estomacal|Sangrado GI|Zumbidos', 'Úlcera|Hemofilia|Asma|Menores 18 años'],

    // ==================== PRIMEROS AUXILIOS ====================
    ['Gel Aloe Vera', 'primeros', 'Cicatrizante natural', 'Quemaduras leves', 'Quemaduras solares|Irritación|Cortes leves', 'https://img.icons8.com/color/96/000000/skin.png', 'Uso tópico exclusivo. No ingerir.', 'Aplicar capa gruesa 2-3 veces al día.', 'Irritación leve|Erupción', 'Hipersensibilidad|Heridas profundas|Quemaduras 3er grado'],
    ['Clorhexidina', 'primeros', 'Antiséptico', 'Desinfección heridas', 'Limpieza heridas|Desinfección quemaduras', 'https://img.icons8.com/color/96/000000/first-aid-kit.png', 'Uso tópico. Evitar ojos y oídos.', 'Aplicar solución diluida. Dejar secar.', 'Irritación|Sequedad cutánea', 'Hipersensibilidad|Perforación timpánica'],
    ['Agua Oxigenada', 'primeros', 'Antiséptico', 'Limpieza heridas', 'Limpieza heridas superficiales', 'https://img.icons8.com/color/96/000000/first-aid-kit.png', 'No usar en heridas profundas.', 'Aplicar directamente. Dejar actuar 1-2 minutos.', 'Irritación|Ardor|Daño tisular', 'Heridas profundas|Ojos|Mucosas'],
    ['Povidona Yodada', 'primeros', 'Antiséptico', 'Desinfección', 'Limpieza heridas|Quemaduras superficiales', 'https://img.icons8.com/color/96/000000/first-aid-kit.png', 'No usar en grandes superficies.', 'Aplicar solución. Dejar secar.', 'Irritación|Dermatitis|Alergia', 'Enfermedad tiroidea|Embarazo|Recién nacidos'],
    ['Crema Antibiótica', 'primeros', 'Antibiótico tópico', 'Prevención infecciones', 'Cortes pequeños|Quemaduras leves', 'https://img.icons8.com/color/96/000000/skin.png', 'Suspender si hay irritación.', 'Aplicar capa fina 1-3 veces al día.', 'Irritación|Erupción|Ardor', 'Hipersensibilidad|Infecciones profundas'],
    ['Solución Salina', 'primeros', 'Limpiador estéril', 'Limpieza heridas', 'Limpieza heridas|Lavado ocular', 'https://img.icons8.com/color/96/000000/first-aid-kit.png', 'Usar estéril. No reutilizar.', 'Irrigar herida. Limpiar con gasa.', 'Irritación leve|Escozor', 'Contaminación del envase'],
    ['Alcohol en Gel', 'primeros', 'Antiséptico', 'Higiene manos', 'Limpieza manos|Desinfección rápida', 'https://img.icons8.com/color/96/000000/sanitizer.png', 'No ingerir. Evitar ojos.', 'Aplicar en manos. Frotar hasta secar.', 'Sequedad|Irritación|Dermatitis', 'Heridas abiertas|Mucosas|Ingestión'],

    // ==================== ENFERMEDADES CRÓNICAS ====================
    ['Metformina', 'enfermedades', 'Antidiabético', 'Diabetes tipo 2', 'Diabetes|Resistencia insulina|SOP', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Tomar con alimentos. Suspender antes cirugía.', '500-850 mg cada 12 horas. Máx 2550 mg/día.', 'Náuseas|Diarrea|Sabor metálico|Acidosis láctica', 'Insuficiencia renal|Hepática|Alcoholismo'],
    ['Insulina Aspart', 'enfermedades', 'Insulina rápida', 'Diabetes', 'Diabetes tipo 1|Diabetes tipo 2 avanzada', 'https://img.icons8.com/color/96/000000/insulin.png', 'Administrar 5-15 min antes comidas.', 'Dosis individualizada 0.5-1 U/kg/día.', 'Hipoglucemia|Lipodistrofia|Aumento peso', 'Hipoglucemia|Hipersensibilidad'],
    ['Enalapril', 'enfermedades', 'IECA', 'Hipertensión crónica', 'Hipertensión|Insuficiencia cardíaca|Nefropatía', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Monitorear función renal y potasio.', '5-40 mg/día en 1-2 dosis.', 'Tos seca|Mareos|Angioedema', 'Embarazo|Estenosis renal'],
    ['Amlodipino', 'enfermedades', 'Bloqueador calcio', 'Hipertensión crónica', 'Hipertensión|Angina|Enfermedad coronaria', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Tomar misma hora. Precaución hepatopatía.', '5-10 mg una vez al día.', 'Edema tobillos|Cefalea|Rubor', 'Hipotensión severa|Shock cardiogénico'],
    ['Atorvastatina', 'enfermedades', 'Estatina', 'Colesterol alto crónico', 'Hipercolesterolemia|Prevención cardiovascular', 'https://img.icons8.com/color/96/000000/cholesterol.png', 'Tomar noche. Reportar dolor muscular.', '10-80 mg/día por la noche.', 'Dolor muscular|Rabdomiólisis|Elevación enzimas', 'Enfermedad hepática|Embarazo|Lactancia'],
    ['Levotiroxina', 'enfermedades', 'Hormona tiroidea', 'Hipotiroidismo crónico', 'Hipotiroidismo|Bocio|Cáncer tiroides', 'https://img.icons8.com/color/96/000000/thyroid.png', 'Tomar en ayunas 30-60 min antes desayuno.', '1.6 mcg/kg/día.', 'Palpitaciones|Insomnio|Pérdida peso', 'Tirotoxicosis|Infarto reciente'],
    ['Alopurinol', 'enfermedades', 'Antigotosos', 'Gota crónica', 'Gota|Hiperuricemia|Nefropatía úrica', 'https://img.icons8.com/color/96/000000/gout.png', 'Tomar después comidas. Aumentar líquidos.', '100-300 mg/día. Máx 800 mg/día.', 'Erupción|Náuseas|Hepatotoxicidad', 'Hipersensibilidad|Insuficiencia renal grave'],
    ['Carbamazepina', 'enfermedades', 'Anticonvulsivante', 'Epilepsia', 'Epilepsia|Neuralgia trigémino|Bipolar', 'https://img.icons8.com/color/96/000000/seizure.png', 'Monitoreo niveles. Riesgo hematológico.', '200-400 mg cada 12 horas. Máx 1600 mg/día.', 'Mareos|Ataxia|Diplopía|Leucopenia', 'Bloqueo AV|Depresión médula ósea|Porfiria'],
    ['Sertralina', 'enfermedades', 'ISRS', 'Depresión y ansiedad', 'Depresión|Ansiedad|TOC|Pánico|TEPT', 'https://img.icons8.com/color/96/000000/depression.png', 'Tarda 2-4 semanas. No suspender bruscamente.', '50-200 mg/día.', 'Náuseas|Insomnio|Disfunción sexual|Aumento peso', 'IMAO|Síndrome serotoninérgico'],
    ['Losartán', 'enfermedades', 'ARA II', 'Hipertensión crónica', 'Hipertensión|Nefropatía diabética|Insuficiencia cardíaca', 'https://img.icons8.com/color/96/000000/blood-test.png', 'Monitorear potasio. Evitar embarazo.', '50 mg/día. Máx 100 mg.', 'Mareos|Hipotensión|Hiperkalemia', 'Embarazo|Estenosis renal|Insuficiencia renal'],
    ['Clopidogrel', 'enfermedades', 'Antiplaquetario', 'Prevención cardiovascular', 'Prevención infarto|Prevención ACV|Post-stent', 'https://img.icons8.com/color/96/000000/heart.png', 'Riesgo sangrado. Suspender antes cirugía.', '75 mg una vez al día.', 'Sangrado|Hematomas|Trombocitopenia', 'Sangrado activo|Úlcera|Insuficiencia hepática'],
    ['Simvastatina', 'enfermedades', 'Estatina', 'Colesterol alto', 'Hipercolesterolemia|Prevención cardiovascular', 'https://img.icons8.com/color/96/000000/cholesterol.png', 'Tomar noche. Reportar dolor muscular.', '10-40 mg/día por la noche.', 'Dolor muscular|Debilidad|Rabdomiólisis', 'Enfermedad hepática|Embarazo|Lactancia'],
    ['Omeprazol', 'enfermedades', 'IBP', 'Reflujo crónico', 'ERGE|Úlcera|Esofagitis|Gastritis', 'https://img.icons8.com/color/96/000000/stomach.png', 'Tomar antes desayuno. Uso prolongado: riesgo B12.', '20-40 mg/día antes desayuno.', 'Cefalea|Diarrea|Deficiencia B12|Fracturas', 'Hipersensibilidad|Enfermedad hepática'],
    ['Gabapentina', 'enfermedades', 'Anticonvulsivante', 'Dolor neuropático', 'Neuropatía diabética|Fibromialgia|Epilepsia', 'https://img.icons8.com/color/96/000000/nerve.png', 'Ajustar dosis en insuficiencia renal.', '300-600 mg cada 8 horas. Máx 3600 mg/día.', 'Somnolencia|Mareos|Ataxia|Edema', 'Hipersensibilidad']
  ];

  for (const m of medicamentos) {
    db.execSync(`
      INSERT INTO medicamentos (nombre, categoria, descripcion, uso, enfermedades, imagen, advertencia, dosificacion, efectos, contraindicaciones)
      VALUES ('${m[0]}', '${m[1]}', '${m[2]}', '${m[3]}', '${m[4]}', '${m[5]}', '${m[6]}', '${m[7]}', '${m[8]}', '${m[9]}')
    `);
  }
};

export const getMedicamentosByCategoria = (categoria: string) => {
  return db.getAllSync('SELECT * FROM medicamentos WHERE categoria = ?', [categoria]);
};

export const searchMedicamentos = (texto: string) => {
  return db.getAllSync(
    'SELECT * FROM medicamentos WHERE nombre LIKE ? OR descripcion LIKE ? OR enfermedades LIKE ?',
    [`%${texto}%`, `%${texto}%`, `%${texto}%`]
  );
};

export const getMedicamentoById = (id: number) => {
  return db.getAllSync('SELECT * FROM medicamentos WHERE id = ?', [id]);
};